on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
       - name: Setup Node.js
         uses: actions/checkout@v3
         with:
          node-version: '16'
      - name: Run build and deploy script
        run: pm install; npm run build; npm run test

      
