on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 * * * *

  jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
13      uses: actions/checkout@v2
14    - name: Run build and deploy script
15      run: |
        npm install
        npm run build
        npm run test

      