name: Dotnet Build Webapp

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Instalar Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

        run: npm install
        run: npm run build
        run: npm test

      